#!/usr/bin/python
# -*- coding: utf-8 -*-
# author: liu   time: 2018/1/17
from user import  *
from twilio.rest import Client

# Find these values at https://twilio.com/user/account
account_sid = ACCOUNT_SID
auth_token = AUTH_TOKEN

client = Client(account_sid, auth_token)
def message():
    client.api.account.messages.create(
        to="+86",
        from_="+",
        body="999999")
    print('发送短信成功')

